config/routes.rb
Rails.application.routes.draw do
  root "articles#index"

  resources :users
  get 'sign_up', to: 'users#new'
  get 'sms', to: 'users#sms'
  delete 'sign_out', to: 'users#sign_out'
  get 'login', to: 'users#login'
  post 'login', to: 'users#login'
  get 'info', to: 'users#info'

  resources :articles do
    resources :comments
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
    include(Visible)
    belongs_to :article
    belongs_to :user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # before_action :set_comment, only: %i[ show edit update destroy ]

  # GET /comments or /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1 or /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments or /comments.json
  def create
    # @comment = Comment.new(comment_params)
    @article = Article.find(params[:article_id])
    @comment = @article.comments.new(comment_params)
    @comment.user_id = current_user['id']
    if @comment.save
      notice = "评论成功"
    else
      notice = "网络故障，请重新评论"
    end

    redirect_to article_path(@article), notice: notice
    # respond_to do |format|
    #   if @comment.save
    #     format.html { redirect_to @comment, notice: "Comment was successfully created." }
    #     format.json { render :show, status: :created, location: @comment }
    #   else
    #     format.html { render :new, status: :unprocessable_entity }
    #     format.json { render json: @comment.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # PATCH/PUT /comments/1 or /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: "Comment was successfully updated." }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: "Comment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:content, :status, :user_id)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<%# @article.comments.each do |comment| %>
    <div class="card shadow-sm border-0 mb-3" style="border-radius: 1em;">
        <div class="row g-0">
            <div class="col-sm-2 text-center card-body">
                <%= image_tag User.find_by(id: comment.user_id).try(:avatar) || "avatar.png", width: "50em" , height: "50em" , class: "rounded-circle" %>
            </div>
            <div class="col-sm-10">
                <div class="card-body">
                    <h5 class="card-title">
                        <%= User.find_by(id: comment.user_id).try(:nickname) || "NICKNAME" %>
                    </h5>
                    <p class="card-text"><%= comment.content %></p>
                    <p class="card-text"><small class="text-muted"><%= comment.created_at %></small></p>
                </div>
            </div>
        </div>
    </div>
<%# end %>

app/views/comments/_form.html.erb
<!-- <%#= form_with(model: comment) do |form| %>
  <%# if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%#= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <%# comment.errors.each do |error| %>
          <li><%#= error.full_message %></li>
        <%# end %>
      </ul>
    </div>
  <%# end %>

  <div class="actions">
    <%#= form.submit %>
  </div>
<%# end %> -->
<%= form_with model: [@article, @article.comments.build] do |form| %>
  <div class="input-group input-group-lg mb-3 border-0" style="background: #EFEFEF;">
    <!-- <input type="text" class="form-control" placeholder="发表你的看法" aria-label="发表你的看法" aria-describedby="button-addon2"> -->
    <!-- <textarea id="search" class="form-control border-0" placeholder="发表你的看法" aria-label="发表你的看法" aria-describedby="button-addon2" required ></textarea> -->
    <%= form.text_area :content, class: "form-control border-0", placeholder: "发表你的看法", 'aria-label': "发表你的看法", "aria-describedby": "button-addon2", required:"required"  %>
    <% if current_user %>
      <button class="btn btn-primary" type="submit" id="button-addon2">评论</button>
    <% else %>
      <%= link_to '评论', login_path, class: "btn btn-primary", id: 'button-addon2' %>
    <% end %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>