config/routes.rb
Rails.application.routes.draw do
  root "articles#index"

  resources :users
  get 'sign_up', to: 'users#new'
  get 'sms', to: 'users#sms'
  delete 'sign_out', to: 'users#sign_out'
  get 'login', to: 'users#login'
  post 'login', to: 'users#login'
  get 'info', to: 'users#info'

  resources :articles do
    resources :comments
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/article.rb
class Article < ApplicationRecord
    include(Visible)
    has_many :comments, dependent: :destroy
    belongs_to :user
    validates :title, presence: true, length: {minimum: 4}, uniqueness: true
    validates :content, presence: true, length: {minimum: 15}
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :check_login, only: %i[ new create edit update destroy ]
  before_action :set_article, only: %i[ show edit update destroy ]

  # GET /articles or /articles.json
  def index
    if params[:search].present?
      @articles = Article.where("title like ?", ['%', params[:search], '%'].join).page(params[:page]).per(3)
    elsif params[:view].present?
      @articles = Article.order(view: :DESC).page(params[:page]).per(3)
    else
      @articles = Article.all.page(params[:page]).per(3)
    end
  end

  # GET /articles/1 or /articles/1.json
  def show
    @title = Article.pluck(:id,:title)
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
    @article = Article.new(article_params)
    @article.user_id = current_user['id']
    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
      @article.update_columns(view: @article.view.to_i+1) if params[:action] == 'show'
    end

    # Only allow a list of trusted parameters through.
    def article_params
      # params.fetch(:article, {})
      params.require(:article).permit(:title,:content, :status, :user_id)
    end

    def check_login
      unless current_user
        redirect_to sign_up_path
      end
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<div class="container">
  <div class="nav align-items-center text-center flex-column justify-content-center">
    <div class="col-sm-12 col-lg-8">
      <%= form_with(model: article, class: "form form-control border-0 pt-5 pb-4 px-4 shadow-lg" ) do |form| %>
        <% if article.errors.any? %>
          <div class="input-group mb-3">
            <div id="error_explanation">
              <h2>
                <%= pluralize(article.errors.count, "error" ) %> prohibited this article from being saved:
              </h2>

              <ul>
                <% article.errors.each do |error| %>
                  <li>
                    <%= error.full_message %>
                  </li>
                  <% end %>
              </ul>
            </div>
          </div>
        <% end %>

        <div class="input-group mb-3">
          <%= form.text_field :title, class: "form-control form-control-lg login-input border-0 main-bg", placeholder: "标题", required: "required" %>
        </div>

        <div class="input-group mb-3">
          <%= form.text_area :content, rows: "10", class: "form-control form-control-lg code login-input border-0 main-bg", placeholder: "这里是博客内容", required: "required" %>
        </div>

        <div class="input-group mb-3">
          <%= form.submit "新建博客" , class: "btn btn-lg btn-primary form-control shadow" %>
        </div>

        <div class="input-group mb-3">
          <%= link_to '返回', articles_path, class: "btn btn-lg btn-outline-primary form-control" %>
        </div>




      <% end %>
    </div>
  </div>
</div>

app/views/articles/_menu.html.erb
<div class="container">
    <div class="d-flex flex-wrap justify-content-md-between">
        <nav class="nav fs-4">
            <a href="/" class="nav-link active ps-0 text-dark fw-bold" aria-current="page" href="#">全部</a>
            <!-- <a href="/?comment=c" class="nav-link text-dark" href="#">评价最多</a> -->
            <a href="/?view=v" class="nav-link text-dark" href="#">访问最多</a>
            <% if current_user %>
              <a class="nav-link text-dark" href="#">我的博客</a>
              <a href="<%= info_path %>" class="nav-link text-dark" href="#">我的信息</a>
            <% end %>
        </nav>
        <form action="/" method="get" class="col-12 col-lg-auto mb-3 mb-lg-0">
            <div class="input-group h-100">
                <input type="text" class="form-control border-0 " name="search" id="search" placeholder="搜索热点" aria-describedby="basic-addon2">
                <!-- <span class="input-group-text border-0" id="basic-addon2"><%#= image_tag "search.png", width: "24" %></span> -->
                <button type="submit" class="input-group-text border-0" id="basic-addon2"><%= image_tag "search.png", width: "24" %></button>
                <!-- <input class="input-group-text bg-light border-0 cred px-3" id="basic-addon2" type="submit" id="" name="" value="" /> -->
            </div>
        </form>
    </div>
</div>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<%= render 'layouts/header' %>
<%= render 'menu' %>
<div class="container">
	<div class="row row-cols-1 row-cols-md-3 g-3 py-3">
		<% cache @articles do %>
      <% @articles.each do |article| %>
        <% cache article do %>
          <a href="<%= article_path(article) %>" target="_self" class=" text-decoration-none text-dark">
            <div class="col">
              <div class="card shadow-lg border-0 p-2">
                <!-- <img src="img/bloglogo.png" class="card-img-top" alt="..."> -->
                <div class="card-body">
                  <h5 class="card-title"><%= article.title %></h5>
                  <p class="card-text text-muted"><%= truncate(article.content) %></p>
                </div>
                <div class=" d-flex text-center justify-content-between p-2">
                  <div class="">
                    <%= image_tag article.user.avatar || "avatar", style: "width: 50px;height: 50px;border-radius: 50%;" %>&nbsp;
										<span class="fs-5"><%= article.user.nickname || 'NICKNAME' %></span>

                  </div>
                  <div class="nav align-items-center">
                      <%= image_tag "view.png", width: "20" %>
                      <span class="fs-6 text-muted">&nbsp; <%= article.view || "1" %></span>
                  </div>
              </div>
              </div>
            </div>
          </a>
        <% end %>
      <% end %>

    <% end %>
	</div>
</div>
<div class="container">
	<div class="row pt-5">
			<%= paginate @articles, theme: 'bootstrap-5', pagination_class: "pagination-sm flex-wrap justify-content-center", nav_class: "d-inline-block" %>
	</div>
</div>
<!-- container end -->

<button type="button" class="btn btn-lg btn-primary position-fixed bottom-0 end-0 m-4 shadow-lg border-0" data-bs-toggle="modal" data-bs-target="#exampleModal" data-bs-whatever="@mdo">
  <a href="<%= new_article_url %>" class="text-light text-decoration-none">写博客</a>
</button>

<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
        <form>
					  <div class="modal-header">
					    <!-- <h5 class="modal-title" id="exampleModalLabel">New message</h5> -->
					    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button> &nbsp;&nbsp;
					    <button type="submit" class="btn-open bg-light border-0" data-bs-dismiss="modal" aria-label="open"> 提交</button>
					  </div>
          <div class="mb-3">
            <label for="recipient-name" class="col-form-label"><h3>标题</h3></label>
            <input type="text" class="form-control" id="recipient-name">
          </div>
          <div class="mb-3">
            <label for="message-text" class="col-form-label"><h3>正文</h3></label>
            <textarea class="form-control" id="message-text"></textarea>
          </div>
        </form>
      </div>
      <!-- <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Send message</button>
      </div> -->
    </div>
  </div>
</div>

app/views/articles/new.html.erb
<%= render 'layouts/header' %>
<%= render 'form', article: @article %>

app/views/articles/show.html.erb
<div class="supports">
	<div class="scope d-flex flex-column ps-4 pt-5">
		<div class="pb-5">
			<a href="<%= root_path %>"><%= image_tag "backbtn.png", width: "48em" %></a>
		</div>
		<div class="pb-3">
			<h5>相关文章</h5>
		</div>
		<div class="">
			<% @title.each do |title| %>
				<p class=""><a href="<%= article_path(title[0]) %>" class="text-decoration-none text-light atitle"><%= title[1] %></a></p>
			<% end %>
		</div>
		<div class="h-100 d-flex"></div>
		<div class="d-flex justify-content-start pb-5 px-0">
			<a href="" class="px-1"><%= image_tag "weibo.png", width: "30em" %> </a>
			<a href="" class="px-1"><%= image_tag "wechat.png", width: "30em" %> </a>
			<a href="" class="px-1"><%= image_tag "twitter.png", width: "30em" %> </a>
			<a href="" class="px-1"><%= image_tag "facebook.png", width: "30em" %> </a>
		</div>
	</div>

	<div class="w-75 pt-5 px-5 text-dark content-right" style="overflow: auto;">
		<div class="content">
			<h1><%= @article.title %></h1>
			<div class="d-flex justify-content-between text-black-50">
				<div class="">
					<%= image_tag @article.user.avatar || "avatar", width: "24em", height: "24em", class: "rounded-circle" %>
					<%= @article.user.nickname || 'NICKNAME' %> &nbsp;
					<%= image_tag "read.png", width: "18em" %> <%= @article.view || 1 %>
				</div>
				<div class="">
					<%= @article.created_at %>
				</div>
			</div>
			<div class="content pt-3">
				<%= @article.content %>
			</div>
		</div>
		<div class="commont pb-5">
			<h1 class="pt-5 pb-4">评论</h1>
			<%= render 'comments/form' %>
			<%= render partial: 'comments/comment', collection: @article.comments %>
		</div>
	</div>
</div>