config/routes.rb
Rails.application.routes.draw do
  root "articles#index"

  resources :users
  get 'sign_up', to: 'users#new'
  get 'sms', to: 'users#sms'
  delete 'sign_out', to: 'users#sign_out'
  get 'login', to: 'users#login'
  post 'login', to: 'users#login'
  get 'info', to: 'users#info'

  resources :articles do
    resources :comments
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles, dependent: :destroy
  has_many :comments, dependent: :destroy

  validates :phone_number, presence: true
  validates :phone_number, uniqueness: true
  has_secure_password
	validates :terms_of_service, acceptance: true


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]
  # invisible_captcha only: [:create, :update], honeypot: :subtitle

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    p params,"||||"
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        session[:user] = @user
        format.html { redirect_to articles_path, notice: "User was successfully updated." }
        # format.html { redirect_to @user, notice: "User was successfully created." }
        # format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        # format.html { redirect_to @user, notice: "User was successfully updated." }
        # format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def sms
    check_phone_number_result = PhoneArea.check(params[:phone])

    if check_phone_number_result[:sp].empty? || !verify_rucaptcha?
      render plain: '电话号码或验证码不正确'
    else
      redis = Redis.new
      redis_phone = redis.get(params[:phone])
			if redis_phone.nil?
				code = sms_code(6)
				p code,"|"
				re = Aliyun::CloudSms.send_msg(params[:phone], 'SMS_192960014', {"code": code})
				p re,"||"
				redis.set(params[:phone], code+",#{Time.now.to_i}")
				render plain: "ok"
			else
				old_time = redis.get(params[:phone]).split(",")[1]
				count_time = (Time.now.to_i-old_time.to_i)/60
				if count_time > 5
					code = sms_code(6)
					p code,"||"
					re = Aliyun::CloudSms.send_msg(params[:phone], 'SMS_192960014', {"code": code})
					redis.set(params[:phone], code+",#{Time.now.to_i}")
					render plain: 'ok'
				else
					render plain: '5minits'
				end
			end
    end
  end

  def login
    if request.post?
      user = User.find_by(phone_number: params[:phone_number]).try(:authenticate, params[:password])
      if user
        session[:user] = user
        redirect_to root_path, notice: '登录成功'
      else
        redirect_to login_path, notice: '账号或密码不正确'
      end
    end
  end

  def sign_out
    session[:user] = nil
    redirect_to root_path, notice: '登出成功'
  end

  def info
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:phone_number, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class="login">
  <div class="container">
    <div class="nav align-items-center text-center flex-column justify-content-center">
      <div class="col-sm-6 col-lg-4">
        <!-- <form action="" method="post" class="form form-control border-0 pt-5 pb-4 px-4 shadow-sm" style="border-radius: 1em;"> -->
        <%= form_with(model: user, class: "form form-control border-0 pt-5 pb-4 px-4 shadow-sm") do |f| %>
          <% if user.errors.any? %>
            <div class="input-group mb-3">
              <div id="error_explanation">
                <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>
                <ul>
                  <% user.errors.each do |error| %>
                    <li><%= error.full_message %></li>
                  <% end %>
                </ul>
              </div>
            </div>
          <% end %>
          
          <div class="input-group mb-3">
            <span class="input-group-text border-0">+86</span>
            <!-- <input type="text" class="form-control form-control-lg phone login-input border-0" placeholder="13800000000" aria-label="phone" aria-describedby="basic-addon1"> -->
            <%= f.text_field :phone_number, class: "form-control form-control-lg phone login-input border-0", placeholder: "13800000000",required: 'required' %>
          </div>

          <div class="input-group mb-3">
            <%= rucaptcha_input_tag(id:'pcode', class: 'form-control form-control-lg code login-input border-0', placeholder: '图形验证码') %>
            <%= rucaptcha_image_tag(alt: 'Captcha', width: '100em') %>
          </div>

          <div class="input-group mb-3">
            <input type="text" name="smscode" class="form-control form-control-lg code login-input border-0" placeholder="短信验证码" required>
            <span class="input-group-text border-0" id="smsbtn">发送验证码</span>
          </div>

          <div class="input-group mb-3">
            <%= f.password_field :password, class: "form-control form-control-lg code login-input border-0", placeholder: "******",required: 'required' %>
          </div>

          <div class="input-group mb-3">
            <%= f.password_field :password_confirmation, class: "form-control form-control-lg code login-input border-0", placeholder: "******",required: 'required' %>
          </div>

          <div class="input-group mb-3">
            <%= f.submit "注册",class: "btn btn-lg btn-primary form-control shadow" %>
          </div>

          <div class="input-group mb-3 d-grid gap-2">
            <!-- <a href="" class="btn btn-lg btn-outline-primary">登录</a> -->
            <%= link_to '登录', login_path, class: "btn btn-lg btn-outline-primary" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/info.html.erb
<%= render 'layouts/header' %>
<%= render 'articles/menu' %>
<div class="container">
	<div class="nav align-items-center text-center flex-column justify-content-center">
		<div class="col-sm-6 col-lg-4">
			<form action="" method="post" class="form form-control border-0 pt-5 pb-4 px-4 shadow-sm" style="border-radius: 1em;">
				<div class="mb-5 position-relative text-center">
					<!-- <img src="img/file.png" width="90" height="90" class="rounded-circle" id="preview" alt="avatar" title="avatar" /> -->
          <%= image_tag 'avatar', width: '90', height: '90',class: 'rounded-circle', id: 'preview', alt: 'avatar', title: 'avatar' %>
          <input type="file" accept="image/*" name="file" id="file" required />
				</div>
				<div class="input-group mb-3">
				  <span class="input-group-text border-0" id="basic-addon1">昵称</span>
				  <input type="text" class="form-control form-control-lg phone login-input border-0" placeholder="NICKNAME" aria-label="phone" aria-describedby="basic-addon1">
				</div>
				<div class="input-group mb-3">
				  <span class="input-group-text border-0" id="basic-addon1">性别</span>
				  <input type="text" class="form-control form-control-lg phone login-input border-0" placeholder="男/女" aria-label="phone" aria-describedby="basic-addon1">
				</div>
				<div class="input-group mb-3">
				  <span class="input-group-text border-0" id="basic-addon1">年龄</span>
				  <input type="text" class="form-control form-control-lg phone login-input border-0" placeholder="0" aria-label="phone" aria-describedby="basic-addon1">
				</div>
				<div class="input-group mb-3">
				  <span class="input-group-text border-0" id="basic-addon1">简介</span>
					<textarea rows="" cols="" class="form-control form-control-lg phone login-input border-0" placeholder="区块链博客真棒" ></textarea>
				</div>
				<div class="pt-4 pb-3 text-center" >
				  <input type="submit" class="btn  btn-primary shadow px-5 py-3 rounded-pill" value="更新" />
				</div>
			</form>
		</div>
	</div>
</div>
<script>
	var fileDom = document.getElementById("file");
	var previewDom = document.getElementById("preview");
	fileDom.addEventListener("change", e => {
		var file = fileDom.files[0];
		if (!file || file.type.indexOf("image/") < 0) {
			fileDom.value = "";
			previewDom.src = "";
			return;
		}
		var fileReader = new FileReader();
		fileReader.onload = e => {
			previewDom.src = e.target.result;
		};
		fileReader.readAsDataURL(file);
	});
	var formDom = document.getElementById("form");
	function check() {
		var file = fileDom.files[0];
		if (!file || file.type.indexOf("image/") < 0) {
			return false;
		}
		return true;
	}
</script>

app/views/users/login.html.erb
<%= render 'layouts/header' %>
<div class="login">
  <div class="container">
    <div class="nav align-items-center text-center flex-column justify-content-center">
      <div class="col-sm-6 col-lg-4">
          <%= notice %>
        <!-- <form action="" method="post" class="form form-control border-0 pt-5 pb-4 px-4 shadow-sm" style="border-radius: 1em;"> -->
          <%= form_with(action: login_path, class: "form form-control border-0 pt-5 pb-4 px-4 shadow-sm") do |f| %>

          <div class="input-group mb-3">
            <span class="input-group-text border-0">+86</span>
            <!-- <input type="text" class="form-control form-control-lg phone login-input border-0" placeholder="13800000000" aria-label="phone" aria-describedby="basic-addon1"> -->
            <%= f.text_field :phone_number, class: "form-control form-control-lg phone login-input border-0", placeholder: "13800000000",required: 'required' %>
          </div>

          <div class="input-group mb-3">
            <%= f.password_field :password, class: "form-control form-control-lg code login-input border-0", placeholder: "******",required: 'required' %>
          </div>

          <div class="input-group mb-3">
            <%= f.submit "登录",class: "btn btn-lg btn-primary form-control shadow" %>
          </div>

          <div class="input-group mb-3 d-grid gap-2">
            <!-- <a href="" class="btn btn-lg btn-outline-primary">注册</a> -->
            <%= link_to '注册', sign_up_path, class: "btn btn-lg btn-outline-primary" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<%= render 'layouts/header' %>
<%= render 'form', user: @user %>
<script>
document.getElementById("smsbtn").addEventListener('click',sendCode);
function sendCode(){
  // document.getElementById("basic-addon2").innerHTML = Date.now();
  var phone_number = document.getElementById("user_phone_number").value;
  var pcode = document.getElementById("pcode").value;
  console.log(phone_number+','+pcode);
  if(phone_number == "" || phone_number == null || typeof phone_number == undefined || phone_number.length < 11){
    alert("请输入电话号码");
  }else if (pcode == "" || pcode == null || typeof pcode == undefined || pcode.length != 5) {
    alert("请输入图形验证码");
  }else{
    console.log("** success **");
    var xmlhttp;
    if (window.XMLHttpRequest)
    {
      xmlhttp=new XMLHttpRequest();
    } else {
      xmlhttp=new ActiveXObject("Microsoft.XMLHTTP");
    }
    xmlhttp.onreadystatechange=function()
    {
      if (xmlhttp.readyState==4 && xmlhttp.status==200)
      {
        let mydata = xmlhttp.responseText;
        console.log(mydata);
        if(mydata=="ok"){
          document.getElementById("smsbtn").value = "已发送";
        }else{
          alert(mydata);
        }
      }
    }
    xmlhttp.open("get","<%= sms_path %>?phone="+phone_number+"&&_rucaptcha="+pcode+"&&t="+Math.random(),true);
    // xmlhttp.setRequestHeader("Content-type","application/x-www-form-urlencoded");
    xmlhttp.send();
  }
}
</script>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>