config/routes.rb
Rails.application.routes.draw do
  root "articles#index"

  resources :users
  get 'sign_up', to: 'users#new'
  get 'sms', to: 'users#sms'
  delete 'sign_out', to: 'users#sign_out'
  get 'login', to: 'users#login'
  post 'login', to: 'users#login'
  get 'info', to: 'users#info'

  resources :articles do
    resources :comments
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_header.html.erb
<div class="container">
  <!-- <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-3"> -->
    <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-between py-3 mb-3">
        <a href="<%= root_path %>" target="_self" class="d-flex align-items-center mb-2 mb-lg-0 text-dark text-decoration-none">
            <%= image_tag "bloglogo.png", width: "200" %>
        </a>
        <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3 bg-primary">
            <!-- <input type="search" class="form-control" placeholder="Search..." aria-label="Search"> -->
        </form>
        <div class="text-end">
          <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
          <!-- <ul class="nav navbar-nav navbar-right cred"> -->
            <% if current_user %>
              <li><%= link_to '登出',sign_out_path, method: :delete, class: "nav-link link-dark text-decoration-none" %></li>
              <li class="nav-item">
                <a class="d-block link-dark text-decoration-none">
                    <span class="fw-bold me-2"><%= current_user[:nickname] || 'NICKNAME' if current_user %></span>
                    <%= image_tag current_user[:avatar] || "avatar", width: "44", height: "44", class: "rounded-circle" %>
                </a>
              </li>
            <% else %>
              <li><a href="<%= login_path %>" class="nav-link px-2 link-secondary">登录</a></li>
              <li>
                <a href="#" target="_self" class="d-block link-dark text-decoration-none">
                    <%= image_tag "avatar", width: "44", height: "44", class: "rounded-circle" %>
                </a>
              </li>
            <% end %>
          </ul>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DbchainBlogRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if notice %>
      <div class="alert alert-success alert-dismissible fade show text-center" role="alert">
        <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Success:"><use xlink:href="#check-circle-fill"/></svg>
        <h4 class="alert-heading">太棒了!</h4>
          <strong> </strong> <%= notice %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>